# Generated by Django 5.0.3 on 2024-03-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(to='escola.professor'),
        ),
    ]
