# Generated by Django 5.0.3 on 2024-03-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_disciplina_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='codigo',
        ),
    ]
