# Generated by Django 5.0.3 on 2024-03-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_remove_disciplina_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
