# Generated by Django 5.0.3 on 2024-03-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_remove_disciplina_professor_disciplina_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
